config/routes.rb
Kandu::Application.routes.draw do
  resources :taskblocks

get 'about' => 'pages#about'

root 'pages#home'

devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  

end

app/models/taskblock.rb
class Taskblock < ActiveRecord::Base
	attr_accessible :description

	validates :description, presence: true

	belongs_to :user
	validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	attr_accessible :email, :password, :password_confirmation, :remember_me, :name

devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauth_providers => [:google_oauth2]
 
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :provider, :uid, :avatar

	has_many :taskblocks, :dependent => :destroy


	# METHODS ---------------------------------------------
  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.username = auth.info.name
        user.email = auth.info.email
        user.avatar = auth.info.image
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in Through Google!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      flash.notice = "You are almost Done! Please provide a password to finish setting up your account"
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/taskblocks_controller.rb
class TaskblocksController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_taskblock, only: [:show, :edit, :update, :destroy]

  # GET /taskblocks
  # GET /taskblocks.json
  def index
    @taskblocks = Taskblock.all
  end

  # GET /taskblocks/1
  # GET /taskblocks/1.json
  def show
  end

  # GET /taskblocks/new
  def new
    @taskblock = current_user.taskblocks.new
  end

  # GET /taskblocks/1/edit
  def edit
    @taskblock = current_user.taskblocks.find(params[:id])
  end

  # POST /taskblocks
  # POST /taskblocks.json
  def create
    @taskblock = current_user.taskblocks.new(params[:taskblock])

    respond_to do |format|
      if @taskblock.save
        format.html { redirect_to @taskblock, notice: 'Taskblock was successfully created.' }
        format.json { render action: 'show', status: :created, location: @taskblock }
      else
        format.html { render action: 'new' }
        format.json { render json: @taskblock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taskblocks/1
  # PATCH/PUT /taskblocks/1.json
  def update
    respond_to do |format|
      if @taskblock.update(taskblock_params)
        format.html { redirect_to @taskblock, notice: 'Taskblock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @taskblock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taskblocks/1
  # DELETE /taskblocks/1.json
  def destroy
    @taskblock = current_user.taskblock.find(params[:id])
    @taskblock.destroy
    respond_to do |format|
      format.html { redirect_to taskblocks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taskblock
      @taskblock = Taskblock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taskblock_params
      params.require(:taskblock).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/taskblocks_helper.rb
module TaskblocksHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
		<small>
		<%= link_to "Kandu App", "http://kanduapp.com" %>
		by Lucas Starbuck
		</small>
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <%= link_to "Kandu", root_path, class: "brand" %>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About',  about_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                        
                        <% if user_signed_in? %>
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                    <li><%= link_to "Login", new_user_session_path %></li>

                        <!-- <li> link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) </li> -->


                      <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Kandu</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            <% end %>	

		<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>

app/views/pages/about.html.erb

<h1>About</h1>
<p>
	<%= link_to "Kandu App", "http://kanduapp.com" %>
	is an app that saves freelance coders and designers money, time and headaches.
</p>


app/views/pages/home.html.erb
<div class="hero-unit">

<h1>Welcome to Kandu</h1>
<p>You've found the home for the
<%= link_to "Kandu App", "http://kanduapp.com" %>
</p>

<p>
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>


	<!-- link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), class: "btn btn-primary" -->

</p>

</div>

app/views/taskblocks/_form.html.erb
<%= simple_form_for(@taskblock, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: { rows: "3"} %>


  <div class="actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/taskblocks/_taskblock.html.erb
	<tr>
        <td><%= taskblock.description %></td>
        <td><%= link_to 'Show', taskblock %></td>
         <% if current_user == taskblock.user %>
        <td><%= link_to 'Edit', edit_taskblock_path(taskblock) %></td>
        <td><%= link_to 'Destroy', taskblock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    
      </tr>

app/views/taskblocks/edit.html.erb
<h1>Editing taskblock</h1>

<%= render 'form' %>

<%= link_to 'Show', @taskblock %> |
<%= link_to 'Back', taskblocks_path %>

app/views/taskblocks/index.html.erb
<h1>Listing taskblocks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <%= render @taskblocks %>
  </tbody>
</table>

<br>

<%= link_to 'New Taskblock', new_taskblock_path %>

app/views/taskblocks/new.html.erb
<h1>New taskblock</h1>

<%= render 'form' %>

<%= link_to 'Back', taskblocks_path %>

app/views/taskblocks/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <p>
              <%= @taskblock.description %>
            </p>
            <p>
              <%= @taskblock.user.name %>
            </p>
            <% if current_user == @taskblock.user %>
                <%= link_to 'Edit', edit_taskblock_path(@taskblock) %> |
            <% end %>
            <%= link_to 'Back', taskblocks_path %>
        </div>
    </div>
</div>